import json
import hashlib
from datetime import datetime, timezone
from typing import Dict, Any, List, Optional, Tuple
from fpdf import FPDF
from ..models.schemas import InvestigationRecord, VerificationResult, EmailDetail

class ForensicPDF(FPDF):
    def header(self):
        self.set_fill_color(15, 23, 42) # Slate 900
        self.rect(0, 0, 210, 24, "F")
        self.set_text_color(56, 189, 248) # Cyan 400
        self.set_font("Helvetica", "B", 14)
        self.cell(0, 10, "PHISHTRACE  |  FORENSIC THREAT INVESTIGATION DOSSIER", align="L")
        self.ln(5)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(148, 163, 184) # Slate 400
        self.cell(0, 5, "CRYPTOGRAPHIC INTEGRITY VERIFICATION & INCIDENT RESPONSE ARTIFACT", align="L")
        self.ln(12)

    def footer(self):
        self.set_y(-18)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(100, 116, 139)
        self.cell(0, 4, "DISCLAIMER: Prototype forensic dossier for incident response and triage. Non-tamper-evident integrity metadata included.", align="C")
        self.ln(4)
        self.cell(0, 4, f"Page {self.page_no()}/{{nb}}  --  Generated by PhishTrace Engine v1.0", align="C")

def compute_json_digest(data: Dict[str, Any]) -> str:
    """Computes SHA-256 of canonical JSON serialized string."""
    encoded = json.dumps(data, sort_keys=True, separators=(',', ':')).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()

class EvidenceVaultService:
    def __init__(self):
        self._investigations: Dict[str, Dict[str, Any]] = {}
        self._audit_logs: List[Dict[str, Any]] = []

    def record_investigation(self, email: EmailDetail) -> InvestigationRecord:
        """Stores investigation artifact, generates export digest, and logs audit record."""
        inv_id = f"INV-{email.id[:8].upper()}-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M')}"
        now_iso = datetime.now(timezone.utc).isoformat()
        
        artifact_data = {
            "investigation_id": inv_id,
            "message_id": email.id,
            "subject": email.subject,
            "sender": email.sender_from,
            "recipient": email.recipient_to,
            "original_message_digest": email.original_digest,
            "risk_score": email.risk_assessment.score,
            "risk_category": email.risk_assessment.category,
            "created_at": now_iso,
            "signals": [s.model_dump() for s in email.risk_assessment.signals],
            "gemma_analysis": email.gemma_analysis.model_dump(),
            "origin_candidate_ip": email.headers.origin_candidate_ip,
            "urls": [u.model_dump() for u in email.urls],
            "attachments": [a.model_dump() if hasattr(a, 'model_dump') else a for a in email.attachments]
        }

        export_digest = compute_json_digest(artifact_data)
        artifact_data["export_digest"] = export_digest

        self._investigations[inv_id] = artifact_data

        # Append to audit record
        self._audit_logs.append({
            "timestamp": now_iso,
            "event": "INVESTIGATION_RECORD_CREATED",
            "investigation_id": inv_id,
            "message_id": email.id,
            "sha256": export_digest,
            "analyst_action": "Initial automated forensic capture"
        })

        return InvestigationRecord(
            investigation_id=inv_id,
            message_id=email.id,
            subject=email.subject,
            sender=email.sender_from,
            risk_score=email.risk_assessment.score,
            risk_category=email.risk_assessment.category,
            original_digest=email.original_digest,
            export_digest=export_digest,
            created_at=now_iso,
            status="Verified"
        )

    def verify_integrity(self, investigation_id: str) -> VerificationResult:
        """
        Recalculates SHA-256 digest of stored investigation record
        and verifies if it strictly matches the registered export digest.
        """
        record = self._investigations.get(investigation_id)
        if not record:
            return VerificationResult(
                investigation_id=investigation_id,
                computed_digest="",
                stored_digest="",
                matches=False,
                verified_at=datetime.now(timezone.utc).isoformat(),
                details="Investigation ID not found in vault registry."
            )

        stored = record["export_digest"]
        # Make a copy without export_digest to re-hash canonical content
        copy_data = {k: v for k, v in record.items() if k != "export_digest"}
        computed = compute_json_digest(copy_data)
        matches = (computed == stored)

        now_iso = datetime.now(timezone.utc).isoformat()
        self._audit_logs.append({
            "timestamp": now_iso,
            "event": "INTEGRITY_VERIFICATION_CHECK",
            "investigation_id": investigation_id,
            "match": matches,
            "analyst_action": "Cryptographic digest validation"
        })

        return VerificationResult(
            investigation_id=investigation_id,
            computed_digest=computed,
            stored_digest=stored,
            matches=matches,
            verified_at=now_iso,
            details="Cryptographic SHA-256 digest matches stored record. Zero alteration detected." if matches else "CRITICAL: Digest mismatch! Record payload has been tampered with or modified."
        )

    def get_investigation(self, identifier: str) -> Optional[Dict[str, Any]]:
        if identifier in self._investigations:
            return self._investigations[identifier]
        for rec in self._investigations.values():
            if rec.get("message_id") == identifier:
                return rec
        return None

    def list_investigations(self) -> List[InvestigationRecord]:
        results = []
        for inv_id, rec in self._investigations.items():
            results.append(InvestigationRecord(
                investigation_id=inv_id,
                message_id=rec["message_id"],
                subject=rec["subject"],
                sender=rec["sender"],
                risk_score=rec["risk_score"],
                risk_category=rec["risk_category"],
                original_digest=rec["original_message_digest"],
                export_digest=rec["export_digest"],
                created_at=rec["created_at"],
                status="Verified"
            ))
        return sorted(results, key=lambda x: x.created_at, reverse=True)

    def get_audit_logs(self) -> List[Dict[str, Any]]:
        return list(reversed(self._audit_logs))

    def generate_pdf_report(self, email: EmailDetail, investigation_id: str) -> bytes:
        """
        Renders a PDF incident dossier with cryptographic hashes,
        scoring breakdown, hop analysis, and actionable remediation steps.
        """
        pdf = ForensicPDF()
        pdf.alias_nb_pages()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=20)

        # Overview Box
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(0, 6, "1. INCIDENT INVESTIGATION SUMMARY", ln=True)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(51, 65, 85)
        
        pdf.cell(40, 5, "Investigation ID:", 0)
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(0, 5, investigation_id, ln=True)
        
        pdf.set_font("Helvetica", "", 9)
        pdf.cell(40, 5, "Original File SHA-256:", 0)
        pdf.set_font("Courier", "", 8)
        pdf.cell(0, 5, email.original_digest, ln=True)

        pdf.set_font("Helvetica", "", 9)
        pdf.cell(40, 5, "Subject:", 0)
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(0, 5, email.subject[:70], ln=True)

        pdf.set_font("Helvetica", "", 9)
        pdf.cell(40, 5, "Sender (From):", 0)
        pdf.cell(0, 5, email.sender_from, ln=True)

        pdf.cell(40, 5, "Recipient (To):", 0)
        pdf.cell(0, 5, email.recipient_to, ln=True)

        pdf.cell(40, 5, "Threat Classification:", 0)
        pdf.set_font("Helvetica", "B", 10)
        risk_color = (220, 38, 38) if email.risk_assessment.score >= 50 else (217, 119, 6) if email.risk_assessment.score >= 25 else (22, 163, 74)
        pdf.set_text_color(*risk_color)
        pdf.cell(0, 5, f"{email.risk_assessment.category.upper()} (Risk Score: {email.risk_assessment.score}/100)", ln=True)
        pdf.ln(3)

        # AI Threat Analysis Box
        pdf.set_text_color(15, 23, 42)
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 6, "2. OPEN-SOURCE AI FORENSIC THREAT ASSESSMENT", ln=True)
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(0, 5, f"Suspected Vector: {email.gemma_analysis.suspected_threat}", ln=True)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(51, 65, 85)
        pdf.multi_cell(0, 4.5, f"Summary: {email.gemma_analysis.summary}")
        pdf.ln(3)

        # Contributing Signals
        pdf.set_text_color(15, 23, 42)
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 6, "3. CORROBORATING DETECTION SIGNALS", ln=True)
        pdf.set_font("Helvetica", "", 8.5)
        for sig in email.risk_assessment.signals[:6]:
            pdf.set_text_color(185, 28, 28) if sig.severity in ["critical", "high"] else pdf.set_text_color(51, 65, 85)
            pdf.cell(5, 4, "-", 0)
            pdf.cell(0, 4, f"[{sig.rule_id}] {sig.description} (Weight: {sig.weight})", ln=True)
        pdf.ln(3)

        # Header Forensics & Relay Origin
        pdf.set_text_color(15, 23, 42)
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 6, "4. HEADER TRACE & RELAY ATTRIBUTION", ln=True)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(51, 65, 85)
        origin_ip = email.headers.origin_candidate_ip or "None Detected"
        geo_str = f"{email.headers.origin_geo.city}, {email.headers.origin_geo.country}" if email.headers.origin_geo else "Unknown"
        pdf.cell(0, 5, f"Earliest Candidate Public IP: {origin_ip} | Location: {geo_str}", ln=True)
        pdf.cell(0, 5, f"Observed Authentication: SPF={email.headers.spf_observed} | DKIM={email.headers.dkim_observed} | DMARC={email.headers.dmarc_observed}", ln=True)
        if email.headers.origin_caveat:
            pdf.set_font("Helvetica", "I", 8)
            pdf.set_text_color(100, 116, 139)
            pdf.multi_cell(0, 4, f"Caveat: {email.headers.origin_caveat}")
        pdf.ln(3)

        # Recommended Next Steps
        pdf.set_text_color(15, 23, 42)
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 6, "5. INCIDENT MITIGATION & SOC RESPONSE", ln=True)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(51, 65, 85)
        pdf.multi_cell(0, 4.5, f"Immediate Step: {email.risk_assessment.recommended_next_step}")
        for act in email.gemma_analysis.recommended_actions:
            pdf.cell(5, 4, ">", 0)
            pdf.cell(0, 4, act, ln=True)

        return bytes(pdf.output())

evidence_vault = EvidenceVaultService()
